/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package triangle;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testMyPoint() {
        assertEquals(
            "Test distance between (0, 0) and (10, 30.5)",
            Math.sqrt(Math.pow(10 - 0, 2) + Math.pow(30.5 - 0, 2)),
            new MyPoint().distance(new MyPoint(10, 30.5)),
            0.000001
        );
    }

    @Test public void testTriangle2D() {
        Triangle2D t1 = new Triangle2D(new MyPoint(2.5, 2), new MyPoint(4.2, 3), new MyPoint(5, 3.5));
        assertEquals("Area should equles to 0.025000", t1.getArea(), 0.025000, 0.000001);
        assertEquals("Perimeter should equles to 5.831182", t1.getPerimeter(), 5.831182, 0.000001);
        assertTrue("(3, 3) is not inside of the triangle", !t1.contains(new MyPoint(3, 3)));
        assertTrue("(2.9, 2)-(4, 1)-(1, 3.4) is not inside of the triangle", !t1.contains(new Triangle2D(
            new MyPoint(2.9, 2), new MyPoint(4, 1), new MyPoint(1, 3.4))));
        assertTrue("(2, 5.5)-(4, -3)-(2, 6.5) overlaps with the triangle", t1.contains(new Triangle2D(
            new MyPoint(2, 5.5), new MyPoint(4, -3), new MyPoint(2, 6.5))));
    }
}
